In [62]:
import torch

In [88]:
mask = torch.zeros((100, ), dtype = torch.bool)
train_index = torch.randperm(mask.shape[0])[:60]
mask[train_index] = 1

In [95]:
def train_val_masks(train_mask, manual_seed = None, train_size = 0.8):
    if manual_seed:
        torch.manual_seed(manual_seed)
    train_index = train_mask.nonzero().squeeze()
    print(train_index)
    min = int(train_size*train_index.shape[0])
    rand_train_index = torch.randperm(train_index.shape[0])
    print(rand_train_index)
    rand_train_index_train_index = rand_train_index[:min]
    rand_train_index_val_index = rand_train_index[min:]

    train_mask = torch.zeros_like(train_mask)
    val_mask = torch.zeros_like(train_mask)
    
    new_train_idx = train_index[rand_train_index_train_index]
    new_val_idx = train_index[rand_train_index_val_index]

    print(new_train_idx)
    print(new_val_idx)

    train_mask[new_train_idx] = 1
    val_mask[new_val_idx] = 1
    return train_mask, val_mask

In [96]:
train_mask, val_mask = train_val_masks(mask, 42)

tensor([ 1,  2,  5,  8, 10, 11, 12, 13, 14, 15, 16, 18, 20, 21, 22, 23, 25, 27,
        28, 29, 31, 32, 34, 35, 37, 41, 42, 43, 44, 45, 47, 50, 51, 52, 55, 57,
        59, 60, 61, 62, 63, 65, 71, 72, 75, 76, 77, 78, 79, 82, 83, 84, 87, 88,
        89, 92, 93, 94, 95, 96])
tensor([42, 35, 52, 55, 22, 15, 40, 30, 26, 47, 38, 16, 10, 50, 41, 37, 31, 32,
        27, 28, 49,  1, 57, 51, 59, 58, 53, 48, 24, 33,  0, 21, 39, 20, 23, 29,
         9, 12, 56, 54, 46, 14, 43, 44,  3,  8, 45, 11,  4, 34, 13, 36, 17, 25,
         6, 19,  7,  5,  2, 18])
tensor([71, 57, 87, 92, 34, 23, 63, 47, 42, 78, 61, 25, 16, 83, 65, 60, 50, 51,
        43, 44, 82,  2, 94, 84, 96, 95, 88, 79, 37, 52,  1, 32, 62, 31, 35, 45,
        15, 20, 93, 89, 77, 22, 72, 75,  8, 14, 76, 18])
tensor([10, 55, 21, 59, 27, 41, 12, 29, 13, 11,  5, 28])
