In [1]:
import sys
 
sys.path.insert(0, "../")

from EnsembleFramework import Framework

In [2]:
import torch
def user_function(kwargs):
    # print(kwargs["summed_neighbors"])
    print(kwargs["original_features"] + kwargs["summed_neighbors"])
    return kwargs["original_features"] + kwargs["summed_neighbors"] #kwargs["updated_features"] + kwargs["summed_neighbors"]

hops_list = [3]

framework = Framework([user_function for i in hops_list], 
                     hops_list=hops_list, ## to obtain best for local neighborhood
                     clfs=[],
                     gpu_idx=0,
                     handle_nan=0.0,
                    attention_configs=[None for i in hops_list])
# test_edge_index = torch.tensor([[1,2,3,4,4,5,6,7,7,7,8,8,9],
#                            [0,0,1,1,0,2,3,3,0,4,4,2,5]], dtype=torch.long)
# test_X = torch.tensor([[0,0,0,0], [1,0,0,0],[0,1,0,0], [0,0,1,0], [0,0,0,1], [1,1,0,0], [1,0,1,0], [1,0,0,1], [0,1,1,0], [0,1,0,1]], dtype=torch.float)

test_X = torch.tensor([[0,0,0,0], [1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1], [1,1,0,0], [1,0,1,0], [1,0,0,1], [0,1,1,0], [0,1,0,1]]).type(torch.float)
test_edge_index = torch.tensor([[9, 8,8,7,7,7,6,5,4,4,3,1,2], [5,2,4,4,0,3,3,2,0,1,1,0,0]])
framework.get_features(test_X, test_edge_index, torch.ones(test_X.shape[0]).type(torch.bool))

tensor([[2., 1., 0., 2.],
        [1., 0., 1., 1.],
        [1., 3., 1., 0.],
        [2., 0., 2., 1.],
        [1., 1., 1., 2.],
        [1., 2., 0., 1.],
        [1., 0., 1., 0.],
        [1., 0., 0., 1.],
        [0., 1., 1., 0.],
        [0., 1., 0., 1.]], device='cuda:0')
tensor([[4., 4., 3., 4.],
        [4., 1., 3., 3.],
        [1., 4., 1., 1.],
        [2., 0., 2., 1.],
        [1., 1., 1., 2.],
        [1., 2., 0., 1.],
        [1., 0., 1., 0.],
        [1., 0., 0., 1.],
        [0., 1., 1., 0.],
        [0., 1., 0., 1.]], device='cuda:0')
tensor([[7., 6., 5., 7.],
        [4., 1., 3., 3.],
        [1., 4., 1., 1.],
        [2., 0., 2., 1.],
        [1., 1., 1., 2.],
        [1., 2., 0., 1.],
        [1., 0., 1., 0.],
        [1., 0., 0., 1.],
        [0., 1., 1., 0.],
        [0., 1., 0., 1.]], device='cuda:0')


[tensor([[7., 6., 5., 7.],
         [4., 1., 3., 3.],
         [1., 4., 1., 1.],
         [2., 0., 2., 1.],
         [1., 1., 1., 2.],
         [1., 2., 0., 1.],
         [1., 0., 1., 0.],
         [1., 0., 0., 1.],
         [0., 1., 1., 0.],
         [0., 1., 0., 1.]], device='cuda:0')]